###register request
post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "alisme12", 
    "email" : "ali2000sme@gmail.com" ,
    "mobile" : "09123610655" ,
    "password" : "alisme12" ,
    "confirm_password" : "alisme12"
}

###login request
post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: bearer {{$dotenv token}}

{
    "username" : "alisme12", 
    "password" : "alisme12" 
}