###register request
post http://localhost:3000/auth/register
Content-Type: application/json

{
    "username" : "ali15", 
    "email" : "ali2002sme@gmail.com" ,
    "mobile" : "09123610657" ,
    "password" : "alisme14" ,
    "confirm_password" : "alisme14"
}

###login request
post http://localhost:3000/auth/login
Content-Type: application/json
Authorization: bearer {{$dotenv token}}

{
    "username" : "alisme13", 
    "password" : "alisme13" 
}